version: "3"
services:

  neo4j-server:
    image: neo4j:4.0.1          
    ports:                    
     - "7474:7474" # used for http
     - "7687:7687" # used for bolt
    environment:       
      NEO4J_AUTH: neo4j/password  
      NEO4J_dbms_connector_http_advertised__address: "localhost:7687"
      NEO4J_dbms_connector_bolt_advertised__address: "localhost:7687"
    networks:
      - service-network

networks:
  service-network:
    driver: bridge