name: .NET Core

on:
  push:
    branches: [ master, GithubActions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEO4J_HOST: neo4j

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      neo4j:
        # Docker Hub image
        image: neo4j:4.0.1
        ports:                    
        - 7474:7474 # used for http
        - 7687:7687 # used for bolt
        env:       
          NEO4J_AUTH: neo4j/password  
          NEO4J_dbms_connector_http_advertised__address: "NEO4J_HOST:7687"
          NEO4J_dbms_connector_bolt_advertised__address: "NEO4J_HOST:7687"

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore  ./src/BbcCorp.Neo4j.NeoGraphManager.sln
    
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/BbcCorp.Neo4j.NeoGraphManager.sln
    
    - name: Run Integration Tests 
      env:
        NEO4J_SERVER: NEO4J_HOST
      run: |
        cd ./src/BbcCorp.Neo4j.Tests
        docker ps
        dotnet test --no-restore --verbosity normal BbcCorp.Neo4j.Tests.csproj
